# Generated by Django 5.0.6 on 2024-08-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50, null=True)),
                ('item_name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('discounted_price', models.DecimalField(decimal_places=0, max_digits=1000000000000000, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('image', models.FileField(null=True, upload_to='items_images')),
            ],
        ),
    ]
