# Generated by Django 5.0.6 on 2024-08-18 23:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_buyers_buy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='user',
            new_name='buyer',
        ),
    ]
