# Generated by Django 5.0.6 on 2024-07-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
