# Generated by Django 5.0.6 on 2024-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_location_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
