# Generated by Django 5.0.6 on 2024-07-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_customeruser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='pfp',
            field=models.FileField(null=True, upload_to='profile-images'),
        ),
    ]
