# Generated by Django 5.0.6 on 2024-08-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_customeruser_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
