# Generated by Django 5.0.6 on 2024-07-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_profile_bio_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
