# Generated by Django 5.0.6 on 2024-06-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField(verbose_name='')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
