# Generated by Django 5.0.6 on 2024-08-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_requester_requestitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requester',
            old_name='User',
            new_name='user',
        ),
    ]
