# Generated by Django 5.0.6 on 2024-06-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_createlisting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
