# Generated by Django 5.0.6 on 2024-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_createlisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='image',
            field=models.FileField(null=True, upload_to='items_images'),
        ),
    ]
