# Generated by Django 5.0.6 on 2024-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_user_requester_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
