# Generated by Django 5.0.6 on 2024-06-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_createlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
