# Generated by Django 5.0.6 on 2024-08-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_requestitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
