# Generated by Django 5.0.6 on 2024-08-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_requestitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='image',
            field=models.FileField(null=True, upload_to='requesteditems-image'),
        ),
    ]
