# Generated by Django 5.0.6 on 2024-08-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_createlisting_discount_createlisting_input_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10000000000000000, null=True),
        ),
    ]
