# Generated by Django 5.0.6 on 2024-08-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_createlisting_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='input_discount',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='discounted_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
