# Generated by Django 5.0.6 on 2024-06-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
