# Generated by Django 5.0.6 on 2024-08-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='input_discount',
            field=models.DecimalField(decimal_places=0, max_digits=100, null=True),
        ),
    ]
