# Generated by Django 5.0.6 on 2024-08-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_discount_cartitem_input_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='input_discount',
        ),
    ]
